version: '3'
services:
  alpine-webdav:
    image: mbagnall/webdav
    network_mode: host
    volumes:
      - ./webdav:/var/webdav
    environment:
      - USERNAME=test
      - PASSWORD=test
      - PORT=8114
    restart: unless-stopped
